---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kimi-k2-0905-vllm
  namespace: llm-kimi-k2-0905
  labels:
    app: kimi-k2-0905
    component: inference-server
spec:
  to:
    kind: Service
    name: kimi-k2-0905-vllm
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
